---
- name: Playbook para instalar la pila LAMP en el FrontEnd
  hosts: frontend1
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Descargar OpenSearch
      get_url:
        url: "https://artifacts.opensearch.org/releases/bundle/opensearch/2.13.0/opensearch-2.13.0-linux-x64.tar.gz"
        dest: "/tmp/opensearch.tar.gz"
        mode: '0755'

    - name: Crear directorio para OpenSearch
      file:
        path: "/opt/opensearch"
        state: directory
        mode: '0755'

    - name: Extraer OpenSearch
      unarchive:
        src: "/tmp/opensearch.tar.gz"
        dest: "/opt/opensearch"
        remote_src: yes

    - name: Eliminar contenido en /var/www/html/
      shell: rm -rf /var/www/html/*

    - name: Descargar e instalar Composer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php
        mode: 0755


    - name: Instalar Composer globalmente
      command: 
        php /tmp/composer-setup.php \
        --install-dir=/usr/local/bin 
        --filename=composer



    - name: Asegurar permisos
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        mode: 0755

    - name: Instalar PHP y los m贸dulos necesarios
      apt: 
        name:
          - unzip  
        state: present

    - name: Cambiar propiedad de los archivos a www-data
      ansible.builtin.file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes

    - name: Establecer permisos 755 en los archivos
      ansible.builtin.file:
        path: /var/www/html
        mode: '0755'
        recurse: yes

    - name: Descargar el c贸digo fuente de Magento
      command: >
        composer create-project 
        --repository-url=https://repo.magento.com/ 
        --prefer-dist 
        magento/project-community-edition /var/www/html/ 

    - name: Configurar las claves de acceso de Magento para Composer
      command: composer config --global http-basic.repo.magento.com 92c5b017e28d7a0c03ccd3e967812cd2 14113789c8b1646641f5ec969e1d28c8
      

    - name: Instalar Magento
      shell: |
        php /var/www/html/bin/magento setup:install \
          --base-url={{ magento.domain }} \
          --db-host={{ ip.BACKEND_PRIVATE_IP }} \
          --db-name={{ db.name }} \
          --db-user={{ db.user }} \
          --db-password={{ db.password }} \
          --admin-firstname="Admin" \
          --admin-lastname="User" \
          --admin-email={{ magento.admin_email }} \
          --admin-user={{ magento.admin_user }} \
          --admin-password={{ magento.admin_password }} \
          --language={{ magento.language }} \
          --currency={{ magento.currency }} \
          --timezone={{ magento.timezone }} \
          --use-rewrites="1"


    - name: Asegurar permisos
      file:
        path: var/www/html/
        owner: www-data
        group: www-data
        mode: 0755


    - name: Copiar configuraci贸n de Apache para Magento
      copy:
        src: ../templates/magento.conf
        dest: /etc/apache2/sites-available/magento.conf
        mode: 0644

    - name: Activar configuraci贸n de Magento en Apache
      command: a2ensite magento.conf


    - name: Copiar el archivo .htaccess al directorio de WordPress
      copy:
        src: ../htaccess/.htaccess
        dest: "{{ magento.directory }}/.htaccess"
        owner: www-data
        group: www-data
        mode: '0644'

  

    - name: Reiniciar el servidor web Apache
      service:
        name: apache2
        state: restarted