---
- name: Playbook para instalar la pila LAMP en el FrontEnd
  hosts: frontend
  become: yes

  tasks:

    - name: Actualizar los repositorios
      apt:
        update_cache: yes

    - name: Instalar el servidor web Apache
      apt:
        name: apache2
        state: present

    - name: Copiar el archivo de configuración de Apache
      copy:
        src: ../templates/magento.conf
        dest: /etc/apache2/sites-available/
        mode: 0755
        
    - name: Habilitar el módulo rewrite de Apache
      apache2_module:
        name: rewrite
        state: present

    - name: Instalar PHP y los módulos necesarios
      apt: 
        name:
          - php
          - libapache2-mod-php
          - php-mysql
          - php-xml
          - php-mbstring
          - php-curl
          - php-zip
          - php-gd
          - php-intl
          - php-soap
          - php-ldap
          - php-opcache
          - php-cli
          - php8.3-bcmath
        state: present

    - name: Modificar memory_limit en php.ini
      lineinfile:
        path: "/etc/php/8.3/apache2/php.ini"
        regexp: '^memory_limit'
        line: 'memory_limit = 2048M'

    - name: Modificar max_execution_time en php.ini
      lineinfile:
        path: "/etc/php/8.3/apache2/php.ini"
        regexp: '^max_execution_time'
        line: 'max_execution_time = 1800'

    - name: Modificar max_input_vars en php.ini
      lineinfile:
        path: "/etc/php/8.3/apache2/php.ini"
        regexp: '^max_input_vars'
        line: 'max_input_vars = 5000'

    - name: Modificar post_max_size en php.ini
      lineinfile:
        path: "/etc/php/8.3/apache2/php.ini"
        regexp: '^post_max_size'
        line: 'post_max_size = 100M'

    - name: Modificar upload_max_filesize en php.ini
      lineinfile:
        path: "/etc/php/8.3/apache2/php.ini"
        regexp: '^upload_max_filesize'
        line: 'upload_max_filesize = 100M'

    - name: Reiniciar el servidor web Apache
      service:
        name: apache2
        state: restarted

