---
- name: Playbook para configurar HTTPS
  hosts: balanceador
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Desinstalar instalaciones previas de Certbot
      apt:
        name: certbot
        state: absent

    - name: Instalar Certbot con snap
      snap:
        name: certbot
        classic: yes
        state: present

    - name: Detener HAProxy para liberar el puerto 80
      systemd:
        name: haproxy
        state: stopped

    - name: Solicitar y configurar certificado SSL/TLS a Let's Encrypt con certbot
      command: certbot certonly --standalone -m {{ certbot.email }} --agree-tos --no-eff-email -d {{ certbot.domain }} --non-interactive


    - name: Reiniciar HAProxy
      systemd:
        name: haproxy
        state: started
