---
- name: Configurar servidor NFS para WordPress
  hosts: nfs
  become: yes

  vars_files:
    - ../vars/variables.yml

  tasks:

    - name: Actualizar repositorios
      apt:
        update_cache: yes


    - name: Instalar NFS Kernel Server
      apt:
        name: nfs-kernel-server
        state: present

    - name: Crear el directorio para WordPress
      file:
        path: /var/www/html
        state: directory
        owner: nobody
        group: nogroup
        mode: 0755

    - name: Copiar el archivo exports
      copy:
        src: ../exports
        dest: /etc/exports
        mode: 0755

    - name: Reemplazar CLIENT_IP en /etc/exports
      replace:
        path: /etc/exports
        regexp: "nfscliente.client_ip"
        replace: "{{ nfscliente.client_ip }}"



    - name: Reiniciar el servidor NFS
      service:
        name: nfs-kernel-server
        state: restarted